version: '3.3'

services:
  database:
    image: andrzejd/hms-database:latest
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=admin

  api:
    image: andrzejd/hms:1.12
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      SPRING_APPLICATION_JSON:
        '{"spring": {"datasource": {"url": "jdbc:mysql://database:3306/hotel_db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false", "username": "root", "password": "admin"}}}'
    restart: on-failure:5
    links:
      - database
